#!/usr/bin/env python3
"""cjk_font.py → hmi-go/internal/font/glyphs_gen.go 转换器。

字库单一事实源是 cjk_font.py(GNU Unifont 子集,Python 回退版仍在用)。
加字流程:改 cjk_font.py → 重跑本脚本 → 重跑 gen_golden_frames.py。
"""
import sys
from pathlib import Path

APP = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(APP))

from cjk_font import GLYPHS  # noqa: E402

OUT = APP / "hmi-go" / "internal" / "font" / "glyphs_gen.go"


def main():
    lines = [
        "// Code generated by tools/gen_font_go.py from cjk_font.py. DO NOT EDIT.",
        "package font",
        "",
        "var glyphHex = map[rune]string{",
    ]
    for ch in sorted(GLYPHS, key=ord):
        assert len(ch) == 1, "GLYPHS key 必须是单字符: %r" % ch
        bm = GLYPHS[ch]
        assert len(bm) in (32, 64), "字形 hex 长度非法: %r %d" % (ch, len(bm))
        disp = ch if (ch.isprintable() and ch != " ") else "U+%04X" % ord(ch)
        lines.append('\t0x%04X: "%s", // %s' % (ord(ch), bm, disp))
    lines += ["}", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    import shutil
    import subprocess
    if shutil.which("gofmt"):  # 保证产物 gofmt 干净(板外开发机必有 go 工具链)
        subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    print("wrote %s (%d glyphs)" % (OUT, len(GLYPHS)))


if __name__ == "__main__":
    main()
