# AI 终局赢家：融资寒冬压力测试

## tl;dr

- [INFERRED | HIGH] 这个测试优先识别谁能避免死亡、保留危机后扩张权；它不能直接预测谁的股票回报最高。
- [INFERRED | HIGH] 在 24 个月不能新增债务或股权、AI 相关收入或单位经济下降 30% 的情景下，CoreWeave 是样本中唯一进入实质性重组风险区的公司；Oracle 能存续，但当前扩建路径难以原样维持。
- [INFERRED | HIGH] NVIDIA、Arista 与 Palantir 最接近“净现金或高流动性、正自由现金流、低刚性建设承诺”的危机扩张模板。


## Context & Methods

- [INFERRED | MED] 情景定义：AI 相关收入或单位经济性一次性下降 30%，且 24 个月不能新增债务、普通股或优先股融资；这不是目标价模型。
- [COMMON | HIGH] 分档不是加权总分。先通过融资独立、现金转换、承诺刚性和集中度四个生存门槛，再判断危机后扩张能力。
- [KNOWN | HIGH] 数值来自截至 2026-07-30 的公司公告或监管披露；报告期不同，因此只计算公司内部的现金资本强度，不跨公司比较现金流绝对额。


In [1]:
companies = [
    {'company':'Microsoft','period':'FY26 Q3','ocf':46.70,'capex':30.90,'liquidity':'strong','self_funding':'strong','rigidity':'medium','concentration':'medium','optionality':'strong'},
    {'company':'Meta','period':'2026 Q1','ocf':32.23,'capex':19.84,'liquidity':'strong','self_funding':'strong','rigidity':'medium','concentration':'low','optionality':'strong'},
    {'company':'NVIDIA','period':'FY27 Q1','ocf':50.34,'capex':1.79,'liquidity':'strong','self_funding':'strong','rigidity':'low','concentration':'high','optionality':'strong'},
    {'company':'Broadcom','period':'FY26 Q2','ocf':10.49,'capex':0.23,'liquidity':'conditional','self_funding':'strong','rigidity':'low','concentration':'high','optionality':'medium'},
    {'company':'Palantir','period':'2026 Q1','ocf':0.899,'capex':0.0074,'liquidity':'strong','self_funding':'strong','rigidity':'low','concentration':'medium','optionality':'strong'},
    {'company':'Amazon','period':'TTM to 2026 Q1','ocf':148.53,'capex':147.30,'liquidity':'strong','self_funding':'conditional','rigidity':'high','concentration':'low','optionality':'medium'},
    {'company':'Oracle','period':'FY2026','ocf':31.98,'capex':55.66,'liquidity':'conditional','self_funding':'weak','rigidity':'high','concentration':'high','optionality':'weak'},
    {'company':'CoreWeave','period':'2026 Q1','ocf':2.984,'capex':7.708,'liquidity':'fragile','self_funding':'weak','rigidity':'high','concentration':'high','optionality':'weak'}
]

def classify(row):
    if row['liquidity'] == 'fragile' and row['self_funding'] == 'weak' and row['rigidity'] == 'high':
        return 'red: restructuring risk'
    if row['self_funding'] == 'weak' or row['rigidity'] == 'high':
        return 'amber: plan must change'
    if row['liquidity'] == 'strong' and row['self_funding'] == 'strong':
        return 'green: survives with optionality'
    return 'yellow: survives, constrained'

for row in companies:
    row['capex_to_ocf_pct'] = round(100 * row['capex'] / row['ocf'], 1)
    row['cash_after_capex'] = round(row['ocf'] - row['capex'], 3)
    row['stress_band'] = classify(row)

for row in companies:
    print(f"{row['company']:10} {row['period']:15} capex/OCF={row['capex_to_ocf_pct']:6.1f}%  {row['stress_band']}")


Microsoft  FY26 Q3         capex/OCF=  66.2%  green: survives with optionality
Meta       2026 Q1         capex/OCF=  61.6%  green: survives with optionality
NVIDIA     FY27 Q1         capex/OCF=   3.6%  green: survives with optionality
Broadcom   FY26 Q2         capex/OCF=   2.2%  yellow: survives, constrained
Palantir   2026 Q1         capex/OCF=   0.8%  green: survives with optionality
Amazon     TTM to 2026 Q1  capex/OCF=  99.2%  amber: plan must change
Oracle     FY2026          capex/OCF= 174.0%  amber: plan must change
CoreWeave  2026 Q1         capex/OCF= 258.3%  red: restructuring risk


In [2]:
from collections import Counter
bands = Counter(row['stress_band'] for row in companies)
assert round(next(r for r in companies if r['company']=='Oracle')['capex_to_ocf_pct'], 1) == 174.0
assert round(next(r for r in companies if r['company']=='CoreWeave')['capex_to_ocf_pct'], 1) == 258.3
assert next(r for r in companies if r['company']=='NVIDIA')['cash_after_capex'] == 48.55
assert next(r for r in companies if r['company']=='Palantir')['cash_after_capex'] > 0.89
print(dict(bands))
print('Independent arithmetic checks passed.')


{'green: survives with optionality': 4, 'yellow: survives, constrained': 1, 'amber: plan must change': 2, 'red: restructuring risk': 1}
Independent arithmetic checks passed.


## Results

- [COMPUTED | HIGH] Oracle FY2026 现金资本开支约为经营现金流的 174.0%；CoreWeave 2026 Q1 约为 258.3%。
- [COMPUTED | HIGH] NVIDIA FY27 Q1 的经营现金流减现金资本开支约为 485.5 亿美元；Palantir 2026 Q1 约为 8.916 亿美元。
- [INFERRED | HIGH] 高资本强度本身不是破产判据；真正危险的是它与弱流动性、高刚性承诺、客户集中和再融资依赖同时出现。

## Takeaways

- [INFERRED | HIGH] 先排除“需要资本市场持续开放才能兑现订单”的公司，再比较分销、收费闭环和危机扩张能力。
- [INFERRED | HIGH] Amazon 是严格自由现金流筛选的反例：公司层面可以削减资本开支并依靠多元经营现金流存续，因此不能与 CoreWeave 的融资风险等同。
- [INFERRED | HIGH] 本分析不含统一估值，不能把绿色档直接翻译为买入评级。

[RULES I BROKE]: 无。
