# 崩盘中的 Berkshire、黄金与 BTC

## tl;dr

- [COMPUTED | HIGH] Berkshire 并未躲过所有崩盘：1974 年市场价格回报约 -48.7%，2008 年约 -31.8%。
- [INFERRED | HIGH] Berkshire 的核心优势不是预测顶部，而是永久资本、持续经营现金流、低强制出售风险和危机中的交易确定性。
- [INFERRED | HIGH] 黄金不是每次股灾的即时对冲；它更受实际利率、美元流动性、政策反应和货币制度影响。
- [INFERRED | HIGH] BTC 常态下更接近高贝塔流动性资产；只有在银行信用受损、政策转松且加密通道完好时，才可能短暂表现出非银行资产属性。


## Context & Methods

### Key Assumptions

- [KNOWN | HIGH] Berkshire 与 S&P 500 使用 Berkshire 股东信中的年度市场价格回报和含股息指数回报。
- [KNOWN | HIGH] 黄金使用公开来源中的年度回报或月度首末值粗算；不同年份口径并不完全一致，所以只用于方向和阶段比较。
- [KNOWN | HIGH] 1929–1933 年黄金处于固定官方价格、禁持与强制兑换制度中，不纳入现代可交易回报序列。
- [INFERRED | MED] BTC 压力数据只描述已观察到的危机窗口，不用于预测下一次价格。


In [1]:
berkshire_returns = [
    {'year':1973, 'berkshire_pct':-2.5, 'sp500_pct':-14.8},
    {'year':1974, 'berkshire_pct':-48.7, 'sp500_pct':-26.4},
    {'year':1987, 'berkshire_pct':4.6, 'sp500_pct':5.1},
    {'year':1999, 'berkshire_pct':-19.9, 'sp500_pct':21.0},
    {'year':2000, 'berkshire_pct':26.6, 'sp500_pct':-9.1},
    {'year':2001, 'berkshire_pct':6.5, 'sp500_pct':-11.9},
    {'year':2002, 'berkshire_pct':-3.8, 'sp500_pct':-22.1},
    {'year':2008, 'berkshire_pct':-31.8, 'sp500_pct':-37.0},
    {'year':2009, 'berkshire_pct':2.7, 'sp500_pct':26.5},
    {'year':2020, 'berkshire_pct':2.4, 'sp500_pct':18.4},
    {'year':2022, 'berkshire_pct':4.0, 'sp500_pct':-18.1},
]
for row in berkshire_returns:
    row['relative_pct_points'] = round(row['berkshire_pct'] - row['sp500_pct'], 1)
    print(row)


{'year': 1973, 'berkshire_pct': -2.5, 'sp500_pct': -14.8, 'relative_pct_points': 12.3}
{'year': 1974, 'berkshire_pct': -48.7, 'sp500_pct': -26.4, 'relative_pct_points': -22.3}
{'year': 1987, 'berkshire_pct': 4.6, 'sp500_pct': 5.1, 'relative_pct_points': -0.5}
{'year': 1999, 'berkshire_pct': -19.9, 'sp500_pct': 21.0, 'relative_pct_points': -40.9}
{'year': 2000, 'berkshire_pct': 26.6, 'sp500_pct': -9.1, 'relative_pct_points': 35.7}
{'year': 2001, 'berkshire_pct': 6.5, 'sp500_pct': -11.9, 'relative_pct_points': 18.4}
{'year': 2002, 'berkshire_pct': -3.8, 'sp500_pct': -22.1, 'relative_pct_points': 18.3}
{'year': 2008, 'berkshire_pct': -31.8, 'sp500_pct': -37.0, 'relative_pct_points': 5.2}
{'year': 2009, 'berkshire_pct': 2.7, 'sp500_pct': 26.5, 'relative_pct_points': -23.8}
{'year': 2020, 'berkshire_pct': 2.4, 'sp500_pct': 18.4, 'relative_pct_points': -16.0}
{'year': 2022, 'berkshire_pct': 4.0, 'sp500_pct': -18.1, 'relative_pct_points': 22.1}


In [2]:
gold_returns = [
    {'year':1973, 'gold_pct':63.8, 'basis':'Fed monthly first-to-last'},
    {'year':1974, 'gold_pct':42.3, 'basis':'Fed monthly first-to-last'},
    {'year':1987, 'gold_pct':20.9, 'basis':'Fed monthly first-to-last'},
    {'year':2000, 'gold_pct':-5.5, 'basis':'Fed monthly year-end'},
    {'year':2001, 'gold_pct':2.5, 'basis':'Fed monthly year-end'},
    {'year':2002, 'gold_pct':24.8, 'basis':'Fed monthly year-end'},
    {'year':2008, 'gold_pct':4.3, 'basis':'WGC calendar-year'},
    {'year':2009, 'gold_pct':29.6, 'basis':'WGC calendar-year'},
    {'year':2020, 'gold_pct':25.0, 'basis':'WGC calendar-year'},
    {'year':2022, 'gold_pct':0.4, 'basis':'WGC calendar-year USD'},
]
for row in gold_returns:
    print(row)


{'year': 1973, 'gold_pct': 63.8, 'basis': 'Fed monthly first-to-last'}
{'year': 1974, 'gold_pct': 42.3, 'basis': 'Fed monthly first-to-last'}
{'year': 1987, 'gold_pct': 20.9, 'basis': 'Fed monthly first-to-last'}
{'year': 2000, 'gold_pct': -5.5, 'basis': 'Fed monthly year-end'}
{'year': 2001, 'gold_pct': 2.5, 'basis': 'Fed monthly year-end'}
{'year': 2002, 'gold_pct': 24.8, 'basis': 'Fed monthly year-end'}
{'year': 2008, 'gold_pct': 4.3, 'basis': 'WGC calendar-year'}
{'year': 2009, 'gold_pct': 29.6, 'basis': 'WGC calendar-year'}
{'year': 2020, 'gold_pct': 25.0, 'basis': 'WGC calendar-year'}
{'year': 2022, 'gold_pct': 0.4, 'basis': 'WGC calendar-year USD'}


In [3]:
by_year = {row['year']: row for row in berkshire_returns}
assert by_year[1974]['relative_pct_points'] == -22.3
assert by_year[2008]['relative_pct_points'] == 5.2
assert by_year[2020]['relative_pct_points'] == -16.0
assert by_year[2022]['relative_pct_points'] == 22.1

gold_by_year = {row['year']: row for row in gold_returns}
assert gold_by_year[2000]['gold_pct'] < 0
assert gold_by_year[2008]['gold_pct'] > 0
assert gold_by_year[2022]['gold_pct'] < 1
print('Independent arithmetic and direction checks passed.')


Independent arithmetic and direction checks passed.


## Results

- [COMPUTED | HIGH] Berkshire 1974 年落后 S&P 500 约 22.3 个百分点；2008 年只少跌约 5.2 个百分点。
- [COMPUTED | HIGH] Berkshire 2020 年落后 S&P 500 约 16.0 个百分点，说明高流动性策略会付出错过快速反弹的成本。
- [COMPUTED | HIGH] Berkshire 2022 年领先 S&P 500 约 22.1 个百分点；这与其能源、保险、铁路、公用事业和现金组合相容，但不能证明单一因果。
- [KNOWN | HIGH] 黄金在 2000 年互联网泡沫破裂初段为负，主要正回报集中到 2002 年；2008 和 2020 年也都出现过危机初期流动性抛售。

## Takeaways

- [INFERRED | HIGH] 价值投资的防线是避免永久资本损失和被迫出售，不是保证净值曲线不回撤。
- [INFERRED | HIGH] 黄金应视为货币、实际利率和信用制度资产；BTC 应视为高贝塔流动性资产加条件性的非银行数字资产。
- [INFERRED | HIGH] 将黄金、BTC 和优质现金流股票统称为避险资产会掩盖它们在危机第一阶段和政策反应阶段的相反行为。

[RULES I BROKE]: 无。
